version: '3.9'

services:
  web:
    image: crpi-5vmn5esi06088rs1.cn-hangzhou.personal.cr.aliyuncs.com/messimeimei/meiss:latest
    container_name: ai-keytech-web
    ports:
      - "80:8000"
    env_file:
      - .env
    volumes:
      - ./data:/data
      - ./static/uploads:/app/static/uploads
    command: >
      sh -c "gunicorn -w 2 -b 0.0.0.0:8000 app:app"
