version: '3.9'

services:
  web:
    build: .
    container_name: ai-keytech-web
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/data
      - ./static/uploads:/app/static/uploads
    command: >
      sh -c "gunicorn -w 2 -b 0.0.0.0:8000 app:app"
