name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to ACR
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_REGISTRY }} -u "${{ secrets.ACR_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.ACR_REGISTRY }}/messimeimei/meiss:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.ACR_REGISTRY }}/messimeimei/meiss:latest

      - name: Deploy on server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            set -e
            echo "===== 更新代码 ====="
            cd /root
            if [ ! -d "aiplatform" ]; then
              git clone -b main https://github.com/Messimeimei/aiplatform.git aiplatform
            fi
            cd aiplatform
            git fetch --all
            git reset --hard origin/main
            echo "当前 commit:" $(git rev-parse HEAD)

            echo "===== 部署容器 ====="
            docker pull ${{ secrets.ACR_REGISTRY }}/messimeimei/meiss:latest
            docker compose down || true
            docker compose up -d

            echo "===== 当前容器 ====="
            docker ps -a
