name: Deploy to Aliyun LTS via Docker Compose

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 把仓库代码同步到服务器（不用服务器装 git）
      - name: Upload files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: ${{ secrets.REMOTE_DIR }}
          # 忽略不必要文件，加速
          rm: true
          strip_components: 0
          overwrite: true

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            cd ${REMOTE_DIR:-/opt/apps/aiplatform}

            # 优先使用 docker compose（plugin），否则回退 docker-compose
            if command -v docker compose >/dev/null 2>&1; then
              COMPOSE="docker compose"
            else
              COMPOSE="docker-compose"
            fi

            $COMPOSE down || true
            $COMPOSE build --pull
            $COMPOSE up -d
            docker image prune -f || true
