name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 拉取代码（Runner 本地，也就是 GitHub 服务器）
      - name: Checkout code
        uses: actions/checkout@v3

      # 登录 ACR
      - name: Log in to ACR
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_REGISTRY }} -u "${{ secrets.ACR_USERNAME }}" --password-stdin

      # 构建 Docker 镜像
      - name: Build Docker image
        run: docker build -t ${{ secrets.ACR_REGISTRY }}/messimeimei/meiss:latest .

      # 推送 Docker 镜像到 ACR
      - name: Push Docker image
        run: docker push ${{ secrets.ACR_REGISTRY }}/messimeimei/meiss:latest

      # 部署到服务器
      - name: Deploy on server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            set -e
            # 保证环境依赖存在
            apt-get update -y
            apt-get install -y git docker-compose-plugin

            echo "===== 清理旧目录并拉取新代码 ====="
            cd /root
            rm -rf aiplatform
            git clone https://github.com/Messimeimei/aiplatform.git aiplatform
            ls -l /root/aiplatform

            echo "===== 部署容器 ====="
            cd /root/aiplatform
            docker pull ${{ secrets.ACR_REGISTRY }}/messimeimei/meiss:latest
            docker compose down || true
            docker compose up -d --build

            echo "===== 当前容器列表 ====="
            docker ps -a
    timeout-minutes: 30
