name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to ACR
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_REGISTRY }} -u "${{ secrets.ACR_USERNAME }}" --password-stdin
    
      - name: Build Docker image
        run: docker build -t ${{ secrets.ACR_REGISTRY }}/messimeimei/meiss:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.ACR_REGISTRY }}/messimeimei/meiss:latest

      - name: Deploy on server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /root/aiplatform
            docker pull ${{ secrets.ACR_REGISTRY }}/messimeimei/meiss:latest
            docker compose down || true
            docker compose up -d --build
            docker ps -a
          command_timeout: 20m
          script_stop: true
      
