name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 拉取代码（在 GitHub Runner 上）
      - name: Checkout code
        uses: actions/checkout@v3

      # 登录 ACR
      - name: Log in to ACR
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login crpi-5vmn5esi06088rs1.cn-hangzhou.personal.cr.aliyuncs.com \
            -u "${{ secrets.ACR_USERNAME }}" --password-stdin

      # 构建镜像
      - name: Build Docker image
        run: docker build -t crpi-5vmn5esi06088rs1.cn-hangzhou.personal.cr.aliyuncs.com/messimeimei/meiss:latest .

      # 推送镜像到 ACR
      - name: Push Docker image
        run: docker push crpi-5vmn5esi06088rs1.cn-hangzhou.personal.cr.aliyuncs.com/messimeimei/meiss:latest

      # 部署到服务器
      - name: Deploy on server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            set -e
            cd /root/aiplatform

            echo "===== 登录 ACR ====="
            echo "${{ secrets.ACR_PASSWORD }}" | docker login crpi-5vmn5esi06088rs1.cn-hangzhou.personal.cr.aliyuncs.com \
              -u "${{ secrets.ACR_USERNAME }}" --password-stdin

            echo "===== 拉取最新镜像并启动 ====="
            docker pull crpi-5vmn5esi06088rs1.cn-hangzhou.personal.cr.aliyuncs.com/messimeimei/meiss:latest
            docker compose down || true
            docker compose up -d

            echo "===== 当前容器 ====="
            docker ps -a
